ALTER TABLE public.mdfe
  ADD COLUMN IF NOT EXISTS tipo_manifesto text NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS ufs_percurso text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS municipio_carregamento_nome text,
  ADD COLUMN IF NOT EXISTS municipio_descarregamento_nome text,
  ADD COLUMN IF NOT EXISTS km_inicial numeric,
  ADD COLUMN IF NOT EXISTS data_saida timestamptz,
  ADD COLUMN IF NOT EXISTS conferente text,
  ADD COLUMN IF NOT EXISTS observacoes text,
  ADD COLUMN IF NOT EXISTS cte_ids uuid[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS chaves_cte_terceiros text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS peso_total numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS quantidade_total numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_total numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS produto_predominante text,
  ADD COLUMN IF NOT EXISTS tipo_carga text,
  ADD COLUMN IF NOT EXISTS ncm text,
  ADD COLUMN IF NOT EXISTS cep_carregamento text,
  ADD COLUMN IF NOT EXISTS cep_descarregamento text,
  ADD COLUMN IF NOT EXISTS coord_carregamento text,
  ADD COLUMN IF NOT EXISTS coord_descarregamento text,
  ADD COLUMN IF NOT EXISTS motorista_nome text,
  ADD COLUMN IF NOT EXISTS motorista_cpf text,
  ADD COLUMN IF NOT EXISTS reboque1_placa text,
  ADD COLUMN IF NOT EXISTS reboque2_placa text,
  ADD COLUMN IF NOT EXISTS contratado_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS contratado_nome text,
  ADD COLUMN IF NOT EXISTS contratado_documento text,
  ADD COLUMN IF NOT EXISTS condutores_extras jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS seguradora_nome text,
  ADD COLUMN IF NOT EXISTS seguradora_cnpj text,
  ADD COLUMN IF NOT EXISTS apolice_numero text,
  ADD COLUMN IF NOT EXISTS averbacao_numero text,
  ADD COLUMN IF NOT EXISTS ciot_numero text,
  ADD COLUMN IF NOT EXISTS ciot_documento text,
  ADD COLUMN IF NOT EXISTS vale_pedagio jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS motivo_rejeicao text;