
ALTER TABLE public.cargas
  ADD COLUMN IF NOT EXISTS tipo text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS cod_buonny text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cod_opentech text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS tolerancia_quebra numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ncm text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS sinonimos text DEFAULT NULL;
